Implement log operations and bloom filter
ethereum/eth1.0-specs pull request #276
Opened 2021-07-22 13:40 UTC by Bhargavasomu

### What was wrong?
LogN operations and the bloom filter weren't implemented.
Related to Issue #232 

### How was it fixed?
Following the frontier yellow paper.

#### Cute Animal Picture

![Put a link to a cute animal picture inside the parenthesis-->](https://www.gannett-cdn.com/media/2020/02/25/USATODAY/usatsports/MotleyFool-TMOT-0107af3a-pet-dog-food.jpg?width=2560)

2021-07-22 13:45 UTC, Bhargavasomu commented
@SamWilsn @lightclient can you please review the code whenever free? Thanks a lot!

2021-07-23 00:02 UTC, SamWilsn requested changes

2021-07-23 00:22 UTC, SamWilsn commented
I hope you don't mind @Bhargavasomu but I took the liberty to apply my own suggestions!

2021-07-23 00:24 UTC, merged

2021-07-23 07:38 UTC, Bhargavasomu commented
Thanks @SamWilsn , your changes look excellent.