Organize methods inside utils.py into separate modules based on functionality
ethereum/eth1.0-specs pull request #303
Opened 2021-08-09 11:50 UTC by voith

### What was wrong?
We are continuously adding helper methods to utils.py without following any structure. We should structure these into modules based on functionality. 

### How was it fixed?
organized methods inside utils.py into separate modules based on functionality

#### Cute Animal Picture

![Put a link to a cute animal picture inside the parenthesis-->](https://peepeth.s3-us-west-1.amazonaws.com/images/backgrounds/uPGo4Wbi/large.jpg)
picture credits: [peepeth.com/fhi](https://peepeth.com/fhi)

2021-08-09 12:29 UTC, voith commented
@SamWilsn @lightclient Can you please review this?

2021-08-10 17:40 UTC, SamWilsn requested changes

2021-08-10 17:40 UTC, SamWilsn commented on src/ethereum/utils/__init__.py
> +Utility functions used in this application.
```suggestion
Utility functions used in this specification.
```

2021-08-10 17:40 UTC, SamWilsn commented on src/ethereum/utils/address.py
> +Address specific utility functions used in this application.
```suggestion
Address specific utility functions used in this specification.
```

2021-08-10 17:40 UTC, SamWilsn commented on src/ethereum/utils/address.py
> +from ethereum.frontier.eth_types import Address
Something in the "parent" module probably shouldn't import something from inside the sub-module.

Case in point, when we introduce  the homestead fork, mypy will complain if we use homestead's `Address` type in `to_address`.

tl;dr `to_address` should be in frontier.

2021-08-10 17:40 UTC, SamWilsn commented on src/ethereum/utils/block.py
> +from ethereum.frontier.eth_types import Block, Header
Hm, I think the same suggestion applies here too. We can't really have `ethereum.frontier` types in `ethereum.utils`. Would an `ethereum.frontier.json` package make sense?

2021-08-10 17:40 UTC, SamWilsn commented on src/ethereum/utils/rlp.py
> +def rlp_hash(data: rlp.RLP) -> Hash32:
Should probably just be in `ethereum.frontier.rlp` :/

2021-08-10 20:47 UTC, SamWilsn commented on src/ethereum/utils/hexadecimal.py
> +from ethereum.frontier.eth_types import Address, Bloom, Root
Whoops, I missed one. I'll put up a PR myself to clean the rest of these up.

2021-08-10 20:47 UTC, SamWilsn approved these changes

2021-08-10 20:47 UTC, merged